export const components = {
  basic: [
    '/components/button',
    '/components/icon',
    '/components/elastic-box',
    // '/components/flex',
  ],
  dataDisplay: [
    '/components/badge',
    '/components/nav-bar',
    // '/components/card',
    // '/components/image',
    '/components/collapse',
    '/components/carousel',
    // '/components/list',
    // '/components/notify',
    '/components/notice-bar',
    '/components/tag',
    '/components/result',
    '/components/tab-bar',
  ],
  dataEntry: [
    '/components/check-box',
    // '/components/date-picker',
    // '/components/image-picker',
    // '/components/input',
    // '/components/number-keyboard',
    // '/components/password-input',
    '/components/radio',
    // '/components/range',
    '/components/search',
    // '/components/slider',
    '/components/stepper',
    '/components/switch',
    // '/components/text-area',
  ],
  feedback: [
    // '/components/modal',
    // '/components/popup',
    // '/components/progress',
    // '/components/toast',
  ],
  gesture: [
    // '/components/pull-to-refresh',
    // '/components/swipe-actionr',
  ],
  other: [
    '/components/count-down',
    // '/components/index-bar',
    // '/components/share-sheet',
    '/components/skeleton',
    '/components/sticky',
    // '/components/timeline',
  ],
}
